DROP TABLE IF EXISTS CUSTOMER CASCADE;
CREATE TABLE CUSTOMER (
    id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    country VARCHAR(128) NOT NULL,
    date_of_birth DATE NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS CUSTOMER_ORDER CASCADE;
CREATE TABLE CUSTOMER_ORDER (
    id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
    amount INTEGER NOT NULL,
    vat DECIMAL NOT NULL,
    PRIMARY KEY (id)
);





